### ISSUE TITLE
Trying to run fastq to db.

### ISSUE THREAD

**Issue by DolapoA** [phe-bioinformatics/snapperdb#23]
I attempted to convert fastq to database as so but I came across the following error:
I can't quite make out what exactly the cause is, I was wondering whether anyone has come across this as I don't really know where to go from here.

python run_snapperdb.py fastq_to_db -c ebg1_config.txt /path/file1-18_R1.fastq.gz /path/file-18_R2.fastq.gz 
Namespace(command='fastq_to_db', config_file='ebg1_config.txt', fastqs=['/path/file1-18_R1.fastq.gz ', '/path/file-18_R2.fastq.gz '], force='N', log_dir='/opt/snapperdb')
[2019-01-09 09:40:26,274] INFO: Version: 1-4
[2019-01-09 09:40:26,274] INFO: Initialising data matrix.
[2019-01-09 09:40:26,289] INFO: Mapping data file with bwa.
[2019-01-09 09:43:35,351] INFO: Creating digitised variants with gatk.
[2019-01-09 09:43:42,999] WARNING: Calling variants returned non-zero exit status.
[2019-01-09 09:43:42,999] WARNING: Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/Partitioner
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructors(Class.java:1651)
	at org.broadinstitute.hellbender.utils.ClassUtils.canMakeInstances(ClassUtils.java:30)
	at org.broadinstitute.hellbender.Main.extractCommandLineProgram(Main.java:317)
	at org.broadinstitute.hellbender.Main.setupConfigAndExtractProgram(Main.java:179)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:201)
	at org.broadinstitute.hellbender.Main.main(Main.java:288)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Partitioner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

[2019-01-09 09:43:42,999] ERROR: VCF was not created.
path/file1-18_R1.filtered.vcf not found ...

This is what my log contains:

2019-01-16 11:54:10,228 snapperdb.fastq_to_vcf  INFO    PARAMS: config = ebg1_config.txt; fastqs = ['path/file2-16_R1.fastq.$
2019-01-16 11:54:10,229 snapperdb.fastq_to_vcf  INFO    Running fastq_to_vcf
2019-01-16 11:54:10,229 snapperdb.fastq_to_vcf  INFO    Parsing config_dict
2019-01-16 11:54:10,229 snapperdb.fastq_to_vcf  INFO    Defining class variables and making output files
2019-01-16 11:54:10,233 snapperdb.fastq_to_vcf  INFO    Running Pheonix

**Comment by timdallman** [comment]
Hi.
Looks like a GATK issue.
What version are you using?  v4 is not currently supported
Tim

**Comment by DolapoA** [comment]
Seems to be resolved, Btw I'm using Gatk 3.7. But I'll get back to you to confirm.

**Comment by DolapoA** [comment]
All's well, you can close this.
I needed to properly source/relaunch my .bash file.
