### ISSUE TITLE
Who is timdallman and why is his username hard-coded into the install? (Problems creating DB)

### ISSUE THREAD

**Issue by jb2cool** [phe-bioinformatics/snapperdb#5]
I've installed snapperdb via git/pip and following your instructions to create the DB i'm having issues

[sisadmin@jb snapperdb]$ snapperdb.py make_snpdb -c ebg4_config.txt
Traceback (most recent call last):
  File "/usr/bin/snapperdb.py", line 8, in <module>
    execfile(__file__)
  File "/home/sisadmin/snapperdb/snapperdb.py", line 12, in <module>
    from snapperdb import parse_config
  File "/usr/bin/snapperdb.py", line 8, in <module>
    execfile(__file__)
  File "/home/sisadmin/snapperdb/snapperdb.py", line 12, in <module>
    from snapperdb import parse_config
ImportError: cannot import name parse_config
[sisadmin@jb snapperdb]$ 

If i instead use the snapperdb.py in ~/snapperdb i get a slightly different error but still an error

[sisadmin@jb snapperdb]$ ./snapperdb.py make_snpdb -c ebg4_config.txt
Namespace(command='make_snpdb', config_file='ebg4_config.txt', fastqs=[], log_dir='/home/sisadmin/snapperdb')
### Cant connect to SnapperDB ebg_4_snps
The SNPdb ebg_4_snps does not exist - running sql to create database
Traceback (most recent call last):
  File "./snapperdb.py", line 270, in <module>
    main()
  File "./snapperdb.py", line 265, in main
    run_command(args)
  File "./snapperdb.py", line 97, in run_command
    make_snpdb(config_dict)
  File "/home/sisadmin/snapperdb/snapperdb/snpdb/__init__.py", line 83, in make_snpdb
    snpdb.make_snpdb()
  File "/home/sisadmin/snapperdb/snapperdb/snpdb/snpdb.py", line 162, in make_snpdb
    conn = psycopg2.connect(make_db_conn_string)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  Ident authentication failed for user "**timdallman**"
[sisadmin@jb snapperdb]$ 

This is a vanilla install of CentOS with a fresh Postgres install so i've not really touched anything yet. Any pointers where to start?

**Comment by jb2cool** [comment]
Ok, some of that was in jest, i do know that Tim is one of the devs for SnapperDB but something is surely wrong with a hard-coded username and i still don't seem to be able ot use this properly

**Comment by ulfschaefer** [comment]
I am not Tim Dallman, but it appears that you are using the default config file under user_configs. I suppose you need to make you own config file with access credentials to your own postgres database and use that.

**Comment by jb2cool** [comment]
ah yes, i see, thanks. I was using the default config/ref genomes purely as they were there ready for me to use
